export type Accidental = 'flat' | null | 'sharp';

/** Stored-on-Note accidental: covers double accidentals needed for note rendering. */
export type DrawnAccidental =
  | 'double-flat'
  | 'flat'
  | null
  | 'natural'
  | 'sharp'
  | 'double-sharp';

export type AccidentalSymbol = '__' | '_' | '' | '=' | '^' | '^^';

export type Quality =
  | 'major'
  | 'minor'
  | 'diminished'
  | 'augmented'
  | 'major-7th'
  | 'minor-7th'
  | 'dominant-7th'
  | 'diminished-7th'
  | 'half-diminished-7th'
  | 'minor-major-7th'
  | 'augmented-major-7th';

export type Clef = 'treble' | 'bass' | 'both';

export type ExerciseType = 'staff' | 'leadsheet';

export type FigureType = 'note' | 'interval' | 'triad' | '7th';

export type NumeralSystem = 'scale-relative' | 'major-referential';

export type DisplayMode = 'major' | 'minor';

/**
 * The 15 supported key signatures. Each entry stores the number of sharps
 * (positive) or flats (negative) and the letter names for both major and
 * relative-minor display.
 */
export interface KeySignature {
  id: string;
  fifths: number;
  majorTonic: string;
  minorTonic: string;
}

export const KEY_SIGNATURES: KeySignature[] = [
  { id: 'Cb', fifths: -7, majorTonic: 'C♭', minorTonic: 'A♭' },
  { id: 'Gb', fifths: -6, majorTonic: 'G♭', minorTonic: 'E♭' },
  { id: 'Db', fifths: -5, majorTonic: 'D♭', minorTonic: 'B♭' },
  { id: 'Ab', fifths: -4, majorTonic: 'A♭', minorTonic: 'F' },
  { id: 'Eb', fifths: -3, majorTonic: 'E♭', minorTonic: 'C' },
  { id: 'Bb', fifths: -2, majorTonic: 'B♭', minorTonic: 'G' },
  { id: 'F', fifths: -1, majorTonic: 'F', minorTonic: 'D' },
  { id: 'C', fifths: 0, majorTonic: 'C', minorTonic: 'A' },
  { id: 'G', fifths: 1, majorTonic: 'G', minorTonic: 'E' },
  { id: 'D', fifths: 2, majorTonic: 'D', minorTonic: 'B' },
  { id: 'A', fifths: 3, majorTonic: 'A', minorTonic: 'F♯' },
  { id: 'E', fifths: 4, majorTonic: 'E', minorTonic: 'C♯' },
  { id: 'B', fifths: 5, majorTonic: 'B', minorTonic: 'G♯' },
  { id: 'F#', fifths: 6, majorTonic: 'F♯', minorTonic: 'D♯' },
  { id: 'C#', fifths: 7, majorTonic: 'C♯', minorTonic: 'A♯' },
];

/**
 * A chord pool entry: stored as scale degree (1-7) and quality, relative to
 * the major mode of the active key signature.
 */
export interface ChordPoolEntry {
  root: number;
  accidental: Accidental;
  quality: Quality;
}

/**
 * Letter + accidental + octave, where octave starts at 0 for the root note.
 * E.g. { letter: 'E', accidental: null, octave: 0 } => "E0".
 *
 * The accidental field stores the *drawn* accidental, which may be a double
 * accidental (notes only, not normally generated by chord construction).
 * 'natural' means an explicit natural sign must be drawn (because the key
 * signature would otherwise alter this letter).
 */
export interface Note {
  letter: string;
  accidental: DrawnAccidental;
  octave: number;
}

/**
 * A single drawn exercise's full payload.
 */
export interface Exercise {
  exerciseType: ExerciseType;
  keySignature: KeySignature;
  figureType: FigureType;
  /** Major or minor display mode for lead sheet rendering. */
  displayMode: DisplayMode;
  /** For lead sheet: the chord pool entry. For staff: the source chord/note. */
  poolEntry: ChordPoolEntry;
  /** Inversion index 0..N-1 applied (0 = root position). */
  inversion: number;
  /** Resolved notes after inversion and octave placement. */
  notes: Note[];
  /** For both-clef placement, the notes split across each clef. */
  trebleNotes?: Note[];
  bassNotes?: Note[];
  /** For staff: the chosen clef placement. */
  clef?: Clef;
  /** Unique key for dedupe within a set (figure type + root + inv + clef). */
  shuffleKey: string;
}
